/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di03_tarea_v02;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class Main_Prueba_Reloj extends javax.swing.JFrame {

    /**
     * Creates new form Main_Prueba_Reloj
     */
    public Main_Prueba_Reloj() {
        initComponents();
    }

    

    //se crea una instancia de la interfaz "alarmEventListener"
    static alarmEventListener events = new alarmEventListener() {

        //Lo que va a suceder cada vez que se produzca un evento determinado.
        @Override
        public void alarm(alarmEvent ev) {
            //Mensaje que se imprime en consola al cambiar el ID
            JOptionPane.showMessageDialog(null, "¡¡¡ALARMA!!!");

        }

    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        chk24h = new javax.swing.JCheckBox();
        btAlarma = new javax.swing.JButton();
        relojDigital1 = new di03_tarea_v02.relojDigital();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reloj Digital");
        setResizable(false);

        chk24h.setSelected(true);
        chk24h.setText("24h");
        chk24h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk24hActionPerformed(evt);
            }
        });

        btAlarma.setText("Establecer Alarma");
        btAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlarmaActionPerformed(evt);
            }
        });

        relojDigital1.setAlarma1(new di03_tarea_v02.alarma(9, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relojDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlarma)
                    .addComponent(chk24h))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(relojDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk24h)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAlarma)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlarmaActionPerformed
        
        
        try{
        
        String respuesta = JOptionPane.showInputDialog("Introduzca la hora de la alarma", "00:00");
        int hora = Integer.parseInt(respuesta.split(":")[0]);
        int minuto = Integer.parseInt(respuesta.split(":")[1]);
        relojDigital1.setAlarma1(new alarma(hora, minuto));
        }catch(Exception e){
            System.err.println("Alarma cancelada o formato no válido.");
        }
    }//GEN-LAST:event_btAlarmaActionPerformed

    private void chk24hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk24hActionPerformed
        if (chk24h.isSelected()) {
            relojDigital1.setTipohora24(true);
        } else {
            relojDigital1.setTipohora24(false);
        }

    }//GEN-LAST:event_chk24hActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Prueba_Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Prueba_Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Prueba_Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Prueba_Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main_Prueba_Reloj miReloj = new Main_Prueba_Reloj();
                miReloj.setVisible(true);

                //añadimos el oyente del evento
                miReloj.relojDigital1.addEventListener(events);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlarma;
    private javax.swing.JCheckBox chk24h;
    private javax.swing.JButton jButton1;
    private di03_tarea_v02.relojDigital relojDigital1;
    // End of variables declaration//GEN-END:variables
}
